### ISSUE TITLE
Help to check config

### ISSUE THREAD

**Issue by jokerigno** [benleb/ad-ench#22] opened 2020-10-14 15:24 UTC
Hi, 

It's still me.

I'm testing also this other AD app and I noticed some issue.

Below the config:

```
ench:
  module: ench
  class: EnCh
  notify: "notify.telegrammarco"
  battery:
    interval_min: 180
    min_level: 20
  unavailable:
    interval_min: 3
```

The issue is that messages related to batteries are sent every 3 minutes against 180.
Moreover with this config unavailable are shown in the log but never sent to the notify service.

**Comment by benleb** [comment] 2020-10-14 15:40
will look into this, thanks

**Comment by jokerigno** [comment] 2020-10-16 12:28
one is glad to be of service

**Comment by benleb** [comment] 2020-10-16 17:24
Are you sure you are using the current 0.7.1? After looking at the code, I could imagine you are running an older version? Or any errors in the log? Your config also looks good - for comparison below is the config I have in use. Which python version do you use?

```yaml
ench:
  module: ench
  class: EnCh
  notify: "notify.mobile_app_ben"
  show_friendly_name: True
  initial_delay_secs: 45
  hass_sensor: "sensor.ench_entities"
  battery:
    interval_min: 75
    min_level: 25
  unavailable:
    interval_min: 15
  stale:
    max_stale_min: 95
    entities: [binary_sensor.cube_wz, device_tracker.ben]
  exclude:
    - group.all_vacuum_cleaners
    - sensor.plug_d80d179904b5_amps
    - sensor.plug_d80d179904b5_volts
    ...
```

**Comment by jokerigno** [comment] 2020-10-20 21:52
I checked and I run 0.71.

I copy/paste your config and made some change on notify to see if now works as expected.

This is what I see in the log:

`020-10-20 23:50:34.795889 INFO ench: 👩‍⚕️ sensor.ench_entities updated: 2 | battery: 2, stale: 0, unavailable: 0
2020-10-20 23:50:34.796785 INFO ench: 👩‍⚕️ 2 entities with low battery levels!
2020-10-20 23:50:34.797279 WARNING AppDaemon: callback check_unavailable() in ench has now completed
2020-10-20 23:50:34.800351 WARNING ench: ench: Entity sensor.ench_entities not found in namespace default
2020-10-20 23:50:34.803414 INFO ench: ⁉️  PORTATILECONCOR Current Username is unavailable | last update: 2020-10-19 17:15:14.648986+00:00
2020-10-20 23:50:34.803799 INFO AppDaemon: ench: Entity sensor.ench_entities created in namespace: default
2020-10-20 23:50:35.130656 INFO ench: ⁉️  PORTATILECONCOR Memory Available is unavailable | last update: 2020-10-19 17:15:14.646706+00:00
2020-10-20 23:50:35.410992 INFO ench: ⁉️  PORTATILECONCOR Memory Total is unavailable | last update: 2020-10-19 17:15:14.646866+00:00
2020-10-20 23:50:35.728003 INFO ench: ⁉️  PORTATILECONCOR Memory Usage is unavailable | last update: 2020-10-19 17:15:14.646622+00:00
2020-10-20 23:50:36.042682 INFO ench: ⁉️  PORTATILECONCOR Memory Used is unavailable | last update: 2020-10-19 17:15:14.646787+00:00
2020-10-20 23:50:36.317921 WARNING AppDaemon: Excessive time spent in utility loop: 5120.0ms, 5120.0ms in check_app_updates(), 0.0ms in other
2020-10-20 23:50:36.320044 INFO ench: ⁉️  PORTATILECONCOR Network #0 - BPS Received is unavailable | last update: 2020-10-19 17:15:14.649151+00:00
2020-10-20 23:50:36.617835 INFO ench: ⁉️  PORTATILECONCOR Network #0 - BPS Sent is unavailable | last update: 2020-10-19 17:15:14.649066+00:00
2020-10-20 23:50:36.925243 INFO ench: ⁉️  PORTATILECONCOR Network #0 - Bytes Received is unavailable | last update: 2020-10-19 17:15:14.647621+00:00
2020-10-20 23:50:37.246799 INFO ench: ⁉️  PORTATILECONCOR Network #0 - Bytes Sent is unavailable | last update: 2020-10-19 17:15:14.647538+00:00
2020-10-20 23:50:37.527600 INFO ench: ⁉️  PORTATILECONCOR Network #0 - IPv4 is unavailable | last update: 2020-10-19 17:15:14.647267+00:00
2020-10-20 23:50:37.837188 INFO ench: ⁉️  PORTATILECONCOR Network #0 - IPv6 is unavailable | last update: 2020-10-19 17:15:14.647350+00:00
2020-10-20 23:50:38.148840 INFO ench: ⁉️  PORTATILECONCOR Network #0 - Speed is unavailable | last update: 2020-10-19 17:15:14.647438+00:00
2020-10-20 23:50:38.466960 INFO ench: ⁉️  PORTATILECONCOR Screen #0 - Height is unavailable | last update: 2020-10-19 17:15:14.649609+00:00
2020-10-20 23:50:38.735835 INFO ench: ⁉️  PORTATILECONCOR Screen #0 - Width is unavailable | last update: 2020-10-19 17:15:14.649508+00:00
2020-10-20 23:50:39.040023 INFO ench: ⁉️  PORTATILECONCOR Storage C - Available Free Space is unavailable | last update: 2020-10-19 17:15:14.647876+00:00
2020-10-20 23:50:39.570560 INFO ench: ⁉️  PORTATILECONCOR Storage C - Format is unavailable | last update: 2020-10-19 17:15:14.648122+00:00
2020-10-20 23:50:39.889791 INFO ench: ⁉️  PORTATILECONCOR Storage C - Label is unavailable | last update: 2020-10-19 17:15:14.648287+00:00
2020-10-20 23:50:40.168041 INFO ench: ⁉️  PORTATILECONCOR Storage C - Total Free Space is unavailable | last update: 2020-10-19 17:15:14.647962+00:00
2020-10-20 23:50:40.475229 INFO ench: ⁉️  PORTATILECONCOR Storage C - Total Storage is unavailable | last update: 2020-10-19 17:15:14.647779+00:00
2020-10-20 23:50:40.793914 INFO ench: ⁉️  PORTATILECONCOR Storage C - Usage is unavailable | last update: 2020-10-19 17:15:14.648208+00:00
2020-10-20 23:50:41.078430 INFO ench: ⁉️  PORTATILECONCOR Storage C - Used Space is unavailable | last update: 2020-10-19 17:15:14.648042+00:00
2020-10-20 23:50:41.404018 INFO ench: ⁉️  PORTATILECONCOR Storage D - Available Free Space is unavailable | last update: 2020-10-19 17:15:14.648465+00:00
2020-10-20 23:50:41.810442 INFO ench: ⁉️  PORTATILECONCOR Storage D - Format is unavailable | last update: 2020-10-19 17:15:14.648736+00:00
2020-10-20 23:50:42.129041 INFO ench: ⁉️  PORTATILECONCOR Storage D - Label is unavailable | last update: 2020-10-19 17:15:14.648906+00:00
2020-10-20 23:50:42.430214 INFO ench: ⁉️  PORTATILECONCOR Storage D - Total Free Space is unavailable | last update: 2020-10-19 17:15:14.648575+00:00
2020-10-20 23:50:42.744127 WARNING AppDaemon: Excessive time spent in utility loop: 5218.0ms, 5218.0ms in check_app_updates(), 0.0ms in other
2020-10-20 23:50:42.746554 INFO ench: ⁉️  PORTATILECONCOR Storage D - Total Storage is unavailable | last update: 2020-10-19 17:15:14.648368+00:00
2020-10-20 23:50:43.065281 INFO ench: ⁉️  PORTATILECONCOR Storage D - Usage is unavailable | last update: 2020-10-19 17:15:14.648816+00:00
2020-10-20 23:50:43.390652 INFO ench: ⁉️  PORTATILECONCOR Storage D - Used Space is unavailable | last update: 2020-10-19 17:15:14.648656+00:00
2020-10-20 23:50:43.665541 INFO ench: ⁉️  PORTATILECONCOR System Boot Time is unavailable | last update: 2020-10-19 17:15:14.649236+00:00
2020-10-20 23:50:43.965498 INFO ench: ⁉️  PORTATILECONCOR System Idle Time is unavailable | last update: 2020-10-19 17:15:14.649403+00:00
2020-10-20 23:50:44.278165 INFO ench: ⁉️  PORTATILECONCOR System Uptime is unavailable | last update: 2020-10-19 17:15:14.649323+00:00
2020-10-20 23:50:44.566535 INFO ench: ⁉️  Salone is unavailable | last update: 2020-10-19 17:15:13.257640+00:00
2020-10-20 23:50:44.871141 INFO ench: ⁉️  Salone is unavailable | last update: 2020-10-19 17:15:13.257861+00:00
2020-10-20 23:50:45.196437 INFO ench: ⁉️  Salone Battery Level is unavailable | last update: 2020-10-19 17:15:13.257362+00:00
2020-10-20 23:50:45.530400 INFO ench: ⁉️  Samsung-Galaxy-S7-edge RX is unavailable | last update: 2020-10-19 17:15:24.095390+00:00
2020-10-20 23:50:45.814600 INFO ench: ⁉️  Samsung-Galaxy-S7-edge TX is unavailable | last update: 2020-10-19 17:15:24.095428+00:00
2020-10-20 23:50:46.123781 INFO ench: ⁉️  Samsung-Galaxy-S7-edge Uptime is unavailable | last update: 2020-10-19 17:15:24.095673+00:00
2020-10-20 23:50:46.438153 INFO ench: ⁉️  Skin Type 1 Safe Exposure Time is unavailable | last update: 2020-10-19 17:15:24.092401+00:00
2020-10-20 23:50:46.754228 INFO ench: ⁉️  Skin Type 2 Safe Exposure Time is unavailable | last update: 2020-10-19 17:15:24.092441+00:00
2020-10-20 23:50:47.030756 INFO ench: ⁉️  Skin Type 3 Safe Exposure Time is unavailable | last update: 2020-10-19 17:15:24.092497+00:00
2020-10-20 23:50:47.478546 INFO ench: ⁉️  Skin Type 4 Safe Exposure Time is unavailable | last update: 2020-10-19 17:15:24.092542+00:00
2020-10-20 23:50:47.800828 INFO ench: ⁉️  Skin Type 5 Safe Exposure Time is unavailable | last update: 2020-10-19 17:15:24.092582+00:00
2020-10-20 23:50:48.112682 INFO ench: ⁉️  Skin Type 6 Safe Exposure Time is unavailable | last update: 2020-10-19 17:15:24.092622+00:00
2020-10-20 23:50:48.388125 INFO ench: ⁉️  Soggiorno Status is unavailable | last update: 2020-10-20 08:36:50.449755+00:00
2020-10-20 23:50:48.704137 WARNING AppDaemon: Excessive time spent in utility loop: 4740.0ms, 4740.0ms in check_app_updates(), 0.0ms in other
2020-10-20 23:50:48.706889 INFO ench: ❓ Temperatura Adele is unknown | last update: 2020-10-19 17:15:13.123761+00:00
2020-10-20 23:50:49.029352 INFO ench: ❓ Temperatura Benjamina is unknown | last update: 2020-10-19 17:15:13.139632+00:00
2020-10-20 23:50:49.340120 INFO ench: ❓ Temperatura Cactii is unknown | last update: 2020-10-19 17:15:13.138665+00:00
2020-10-20 23:50:49.669154 INFO ench: ❓ Temperatura Cuciphotos is unknown | last update: 2020-10-19 17:15:13.126588+00:00
2020-10-20 23:50:50.009555 INFO ench: ❓ Temperatura Fortunata is unknown | last update: 2020-10-19 17:15:13.125249+00:00
2020-10-20 23:50:50.338654 INFO ench: ❓ Temperatura Patty is unknown | last update: 2020-10-19 17:15:13.137584+00:00
2020-10-20 23:50:50.623364 INFO ench: ❓ Temperatura Vita is unknown | last update: 2020-10-19 17:15:13.120961+00:00
2020-10-20 23:50:50.938638 INFO ench: ❓ Temperatura Vita Grande is unknown | last update: 2020-10-19 17:15:13.122640+00:00
2020-10-20 23:50:51.317259 INFO ench: ❓ TV accesa is unknown | last update: 2020-10-19 17:15:13.401396+00:00
2020-10-20 23:50:51.730401 INFO ench: ❓ Umidità Adele is unknown | last update: 2020-10-19 17:15:13.124217+00:00
2020-10-20 23:50:52.013220 INFO ench: ❓ Umidità Benjamina is unknown | last update: 2020-10-19 17:15:13.139957+00:00
2020-10-20 23:50:52.333052 INFO ench: ❓ Umidità Cactii is unknown | last update: 2020-10-19 17:15:13.138947+00:00
2020-10-20 23:50:52.651969 INFO ench: ❓ Umidità Cuciphotos is unknown | last update: 2020-10-19 17:15:13.136625+00:00
2020-10-20 23:50:52.991519 INFO ench: ❓ Umidità Fortunata is unknown | last update: 2020-10-19 17:15:13.125770+00:00
2020-10-20 23:50:53.371249 INFO ench: ❓ Umidità Patty is unknown | last update: 2020-10-19 17:15:13.137947+00:00
2020-10-20 23:50:53.746033 INFO ench: ❓ Umidità Vita is unknown | last update: 2020-10-19 17:15:13.122303+00:00
2020-10-20 23:50:54.099754 INFO ench: ❓ Umidità Vita Grande is unknown | last update: 2020-10-19 17:15:13.123017+00:00
2020-10-20 23:50:54.426878 INFO ench: ⁉️  vacuumbin is unavailable | last update: 2020-10-19 17:15:24.095817+00:00
2020-10-20 23:50:54.785971 INFO ench: ⁉️  Veranda Camera di Adele Status is unavailable | last update: 2020-10-20 08:36:50.287425+00:00
2020-10-20 23:50:55.124741 INFO ench: ⁉️  WAQI Alpini, Cuneo, Piemonte, Italy is unavailable | last update: 2020-10-19 17:15:24.093080+00:00
2020-10-20 23:50:55.592958 WARNING AppDaemon: Excessive time spent in utility loop: 5587.0ms, 5587.0ms in check_app_updates(), 0.0ms in other`

the notify message only report 2 battery low.

**Comment by benleb** [comment] 2020-10-25 08:43
do you see this warning when ench is not enabled at all too?
`2020-10-20 23:50:55.592958 WARNING AppDaemon: Excessive time spent in utility loop: 5587.0ms, 5587.0ms in check_app_updates(), 0.0ms in other `

**Comment by jokerigno** [comment] 2020-10-25 14:57
No. I checked the log and this message is absent when ench is disabled.

**Comment by benleb** [comment] 2020-10-25 18:18
hm do you have many unavailables? and a raspi or other low level hardware? Looks like it spends very much time to get through your entities :D

You could try to disable the other checks (and maybe other appdaemon apps) to check if it works if there is less load/no other parallel checks.

**Comment by jokerigno** [comment] 2020-10-26 15:44
Yes I had many unavailables. I made some cleaning and will update on new results shortly.

I'm running HA on a VM inside my Unraid Server so resources should be ok! :)

**Comment by benleb** [comment] 2020-10-27 15:13
hm and the thing with the 2/3min interval... you just have this issue with one of the three checks?! as its the same code for all three, would be very weird if one behaves differently...  this gets a really interesting bug... 😁

**Comment by jokerigno** [comment] 2020-10-28 13:15
yeah it's strange.

this is the code.

```
ench:
  module: ench
  class: EnCh
  notify: "notify.xxxxxxxxxxxxx"
    battery:
    interval_min: 180
    min_level: 20
  unavailable:
    interval_min: 15
```

Unavailable notification are sent every 2 min.

**Comment by benleb** [comment] 2020-10-30 19:44
please try with the master now, I changed some things... (but I still do not know what's wrong and just hope :D)

The next step would be to activate debug logging in appdaemon, that will give you a massive amount of more information

**Comment by jokerigno** [comment] 2020-11-01 12:41
I reinstalled the app but still receiving messages every 2 minutes.

**Comment by jokerigno** [comment] 2020-11-01 13:10
How can I enable debug log?

**Comment by jokerigno** [comment] 2020-11-22 17:13
I saw the update but cannot find any link to this issue. It has been fixed now?

**Comment by benleb** [comment] 2020-11-22 17:21
debug logging: https://appdaemon.readthedocs.io/en/dev/INSTALL.html?highlight=debug#appdaemon-arguments

Maybe? I don’t know as I don’t know the cause 😅 but maybe the debug logs can enlighten us!

But updating should not make it worse, so... 👍😄

**Comment by benleb** [comment] 2020-12-08 14:33
More than two weeks ago since last comment, closing for now... I guess this is either it is working as expected for you now or EnCh has lost one of its users :(

If you still need help debugging this or anything, just comment and I will reopen :)

**Closed by benleb** 2020-12-08 14:33 UTC
Labels: bug, help wanted
